// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfqDI_7DzqEzW-JmfvQBf3gzdzda4B9g0',
    appId: '1:1039693334717:web:5968150d93aeab9f694fd4',
    messagingSenderId: '1039693334717',
    projectId: 'netflixcrudproyectonava',
    authDomain: 'netflixcrudproyectonava.firebaseapp.com',
    storageBucket: 'netflixcrudproyectonava.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANcqjJPxlJQP0IBJyTvjywoyg_3YHHhJI',
    appId: '1:1039693334717:android:bb4a3ab39af9fcdc694fd4',
    messagingSenderId: '1039693334717',
    projectId: 'netflixcrudproyectonava',
    storageBucket: 'netflixcrudproyectonava.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfqDI_7DzqEzW-JmfvQBf3gzdzda4B9g0',
    appId: '1:1039693334717:web:1c71b981c7b365a6694fd4',
    messagingSenderId: '1039693334717',
    projectId: 'netflixcrudproyectonava',
    authDomain: 'netflixcrudproyectonava.firebaseapp.com',
    storageBucket: 'netflixcrudproyectonava.firebasestorage.app',
  );
}
